### ISSUE TITLE
How to set the feedback_aug value?

### ISSUE THREAD

**Issue by mywebinfo65536** [bfshi/AbSViT#2]
Hi, thanks for sharing your work,  but could you tell me how to set the  **self.feedback_aug** value in your absvit.py  when deal with different scence ?

**Comment by bfshi** [comment]
Hi, it's normally set to 1 for vision-only tasks, and set to a larger value like 5 for vision-language tasks.

**Comment by mywebinfo65536** [comment]
thanks.
